#!/bin/bash/env groovy

def colorList= ['BLACK', 'WHITE']

def colorChoices = colorList.join("\n")

parameters([
 choice(choices: colorChoices, description'', name: 'color'),
 string(defaultvalue:'www.google.com', description: 'provide the url', name: 'URL')
])

stage ('Test'){
 echo ${color}
 echo ${URL}
 echo ""first file"
}

